#! /bin/bash -l 
#PBS -l nodes=3:ppn=30 
#PBS -l walltime=48:00:00 
#PBS -l pmem=6gb 
#PBS -m abe 
#PBS -M enora.geslain@student.kuleuven.be 
#PBS -N bwa_alignment_trem
#PBS -A llp_lbeg

cd /Example/;

# Programs needed
module purge
module load BWA/0.7.17-foss-2018a
module load SAMtools/1.9-foss-2018a

date;

while read line
do
	# Variable initialisation
	SAMPLE=$line
	READ1=/Example/cleaned/${SAMPLE}.1.fq.gz
	READ2=/Example/cleaned/${SAMPLE}.2.fq.gz
	BWA_DB=./genome/bwa/tre_ber #Corresponds to the prefix you choose when you indexed your genome
	OUTPUT=./alignments/
	
	# Script
	bwa mem -M -t 90 $BWA_DB $READ1 $READ2 | samtools view -b | samtools sort --threads 10 > $OUTPUT/${SAMPLE}.bam
done < ./info/liste_all_ind.txt #Corresponds to a file containing all the names of your samples (1 per line)

date;

exit 0;
