#! /bin/bash -l
#PBS -l nodes=1:ppn=5
#PBS -l walltime=1:00:00
#PBS -l pmem=10gb
#PBS -m abe
#PBS -M enora.geslain@student.kuleuven.be
#PBS -N populations_r80_M2_trem
#PBS -A llp_lbeg

M=2

cd Example/tests.denovo;

# Programs needed
module purge
module load Stacks/2.5-foss-2018a

date;

# Variable initialisation
STACKS_DIR=./stacks.M${M}
OUTDIR=$STACKS_DIR/populations_r80

# Script
populations \
-P $STACKS_DIR \
-O $OUTDIR \
-r 0.80 \
-t 10 \
&> populations_r80_M${M}.oe;

date;

exit 0;
